version: 2.1

jobs:
  e2e-tests:

    docker:
      - image: cimg/node:24.0

    steps:

      - checkout
      
      - run:
          name: Instalando dependências
          command: npm ci

      - run:
          name: Instalando Browsers Playwright
          command: npx playwright install --with-deps

      - run:
          name: Executando testes
          command: npm run e2e

      - store_artifacts:
          path: playwright-report
          destination: playwright-report

workflows:  

  manual-workflow:
    jobs:
      - e2e-tests